import { useEffect, useRef, useState } from 'react';
import { Check, Copy, Download, FileImage, ImageUp, RotateCcw, Sparkles, WandSparkles } from 'lucide-react';
import charPixelMark from './assets/charpixel-mark.png';
const RAMP = '@%#*+=-:. ';
const Brand = ({ as: Tag = 'div', ...props }) => <Tag {...props} className={`brand ${props.className || ''}`}><span>CharPixel</span><img className="brand-mark" src={charPixelMark} alt="ASCII hand and cursor" /></Tag>;
const AuraButton = ({ children, className = '', ...props }) => <div className={`aura aura-glow ${className}`}><button {...props}>{children}</button></div>;
const ASCIIText = ({ text }) => <span className="ascii-text" aria-label={text}>{text.split('').map((c, i) => <span style={{ '--i': i }} key={`${c}-${i}`}>{c}</span>)}</span>;
const PatternWaves = () => <div className="pattern-waves" aria-hidden="true"><i /><i /><i /></div>;
const PixelCard = ({ children }) => <div className="pixel-card"><div className="pixel-grid" aria-hidden="true" />{children}</div>;
function toAscii(src, columns) { return new Promise((resolve, reject) => { const image = new Image(); image.onload = () => { const width = Math.max(20, Number(columns)); const height = Math.max(1, Math.round(image.height / image.width * width * .48)); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d', { willReadFrequently: true }); ctx.drawImage(image, 0, 0, width, height); const { data } = ctx.getImageData(0, 0, width, height); let result = ''; for (let y = 0; y < height; y += 1) { for (let x = 0; x < width; x += 1) { const p = (y * width + x) * 4; const b = (data[p] * .299 + data[p + 1] * .587 + data[p + 2] * .114) / 255; result += RAMP[Math.min(RAMP.length - 1, Math.floor(b * RAMP.length))]; } result += '\n'; } resolve(result); }; image.onerror = () => reject(new Error('That image could not be read.')); image.src = src; }); }
export default function App() {
  const [started, setStarted] = useState(false); const [imageSrc, setImageSrc] = useState(''); const [imageName, setImageName] = useState(''); const [ascii, setAscii] = useState(''); const [columns, setColumns] = useState(90); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [copied, setCopied] = useState(false); const fileInput = useRef();
  useEffect(() => () => { if (imageSrc) URL.revokeObjectURL(imageSrc); }, [imageSrc]);
  useEffect(() => { if (!imageSrc || !ascii) return; let active = true; toAscii(imageSrc, columns).then(result => { if (active) setAscii(result); }); return () => { active = false; }; }, [columns]);
  const acceptImage = file => { if (!file?.type.startsWith('image/')) return setMessage('Choose a PNG, JPG, WebP, or GIF image.'); if (imageSrc) URL.revokeObjectURL(imageSrc); setImageSrc(URL.createObjectURL(file)); setImageName(file.name); setAscii(''); setMessage('Preview ready. Tune the detail, then convert.'); };
  const convert = async () => { if (!imageSrc) return setMessage('Upload an image first.'); setBusy(true); setMessage('Translating pixels into glyphs…'); try { setAscii(await toAscii(imageSrc, columns)); setMessage('Conversion complete.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const save = (href, name) => { const link = document.createElement('a'); link.href = href; link.download = name; link.click(); };
  const copy = async () => { await navigator.clipboard.writeText(ascii); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  const downloadText = () => save(URL.createObjectURL(new Blob([ascii], { type: 'text/plain' })), `${imageName.replace(/\.[^/.]+$/, '') || 'charpixel'}.txt`);
  const downloadPng = () => { const lines = ascii.trimEnd().split('\n'); const s = 2; const f = 10 * s; const p = 22 * s; const canvas = document.createElement('canvas'); const ctx = canvas.getContext('2d'); ctx.font = `${f}px monospace`; canvas.width = Math.ceil(Math.max(...lines.map(line => ctx.measureText(line).width)) + p * 2); canvas.height = lines.length * f * 1.05 + p * 2; ctx.fillStyle = '#0d0d0f'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.font = `${f}px monospace`; ctx.fillStyle = '#f4f1e8'; ctx.textBaseline = 'top'; lines.forEach((line, i) => ctx.fillText(line, p, p + i * f * 1.05)); save(canvas.toDataURL('image/png'), `${imageName.replace(/\.[^/.]+$/, '') || 'charpixel'}-ascii.png`); };
  if (!started) return <main className="landing"><PatternWaves /><nav><Brand /><p>IMAGE → ASCII</p></nav><PixelCard><section className="hero"><p className="eyebrow">A tiny image translation studio</p><h1>Turn pixels into <em>characters.</em></h1><p className="hero-copy">Drop in an image, find its texture in type, and take the result anywhere.</p><AuraButton className="start-aura" onClick={() => setStarted(true)}><ASCIIText text="Get Started" /><span className="arrow">↗</span></AuraButton><p className="quiet">Runs locally in your browser. Nothing is uploaded.</p></section></PixelCard></main>;
  return <main className="studio"><PatternWaves /><header><Brand as="button" className="home" onClick={() => setStarted(false)} /><div className="status"><span /> Local processing</div></header><section className="studio-title"><div><p className="eyebrow">IMAGE TRANSLATOR</p><h1>Image to <em>ASCII</em></h1></div><button className="reset" onClick={() => { setImageSrc(''); setAscii(''); setMessage(''); }}><RotateCcw size={15} /> Start over</button></section><section className="workspace"><div className="panel source-panel"><div className="panel-label"><span>01 / SOURCE IMAGE</span>{imageName && <small>{imageName}</small>}</div>{imageSrc ? <img className="preview-image" src={imageSrc} alt="Your uploaded preview" /> : <label className="dropzone" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); acceptImage(e.dataTransfer.files[0]); }}><input ref={fileInput} type="file" accept="image/*" onChange={e => acceptImage(e.target.files[0])} /><ImageUp size={31} /><strong>Drop an image here</strong><span>or click to browse your files</span><small>PNG, JPG, WebP, GIF</small></label>}<div className="source-actions">{imageSrc && <button onClick={() => fileInput.current?.click()}><FileImage size={16} /> Replace image</button>}<input ref={fileInput} className="hidden-file" type="file" accept="image/*" onChange={e => acceptImage(e.target.files[0])} /></div></div><div className="panel output-panel"><div className="panel-label"><span>02 / ASCII OUTPUT</span>{ascii && <small>{columns} columns</small>}</div>{ascii ? <pre>{ascii}</pre> : <div className="output-empty"><Sparkles size={30} /><p>Your converted artwork will appear here.</p></div>}</div></section><section className="controls"><div className="detail"><label htmlFor="detail">Character detail <b>{columns}</b></label><input id="detail" type="range" min="40" max="140" value={columns} onChange={e => setColumns(e.target.value)} /><div><span>Minimal</span><span>Detailed</span></div></div><p className="message">{ascii ? 'Adjust the slider for a live preview.' : message}</p><div className="actions"><AuraButton className="convert-aura" disabled={!imageSrc || busy} onClick={convert}><WandSparkles size={17} /> {busy ? 'Converting…' : ascii ? 'Refresh ASCII' : 'Convert to ASCII'}</AuraButton>{ascii && <><button className="secondary" onClick={copy}><Copy size={16} /> {copied ? 'Copied!' : 'Copy'}</button><button className="secondary" onClick={downloadText}><Download size={16} /> Download .txt</button><button className="secondary" onClick={downloadPng}><Download size={16} /> Download PNG</button></>}</div></section>{ascii && <div className="success"><Check size={15} /> Ready to copy, download text, or share the PNG.</div>}</main>;
}
